# Generated by Django 4.1.3 on 2022-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_email_remove_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGScode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('code', models.PositiveIntegerField(max_length=5)),
            ],
        ),
    ]
