# Generated by Django 4.1.3 on 2022-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rgscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgscode',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
